package com.dell.fortune.pocketexpression.model.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dell.fortune.pocketexpression.model.dao.LocalExpressionItem;

import com.dell.fortune.pocketexpression.model.dao.LocalExpressionItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig localExpressionItemDaoConfig;

    private final LocalExpressionItemDao localExpressionItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        localExpressionItemDaoConfig = daoConfigMap.get(LocalExpressionItemDao.class).clone();
        localExpressionItemDaoConfig.initIdentityScope(type);

        localExpressionItemDao = new LocalExpressionItemDao(localExpressionItemDaoConfig, this);

        registerDao(LocalExpressionItem.class, localExpressionItemDao);
    }
    
    public void clear() {
        localExpressionItemDaoConfig.clearIdentityScope();
    }

    public LocalExpressionItemDao getLocalExpressionItemDao() {
        return localExpressionItemDao;
    }

}
