/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dell_fortune_pocketexpression_util_common_JNIUtil */

#ifndef _Included_com_dell_fortune_pocketexpression_util_common_JNIUtil
#define _Included_com_dell_fortune_pocketexpression_util_common_JNIUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dell_fortune_pocketexpression_util_common_JNIUtil
 * Method:    getSignature
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dell_fortune_pocketexpression_util_common_JNIUtil_getSignature
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
